In [2]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim: ", t_array.dim, "shape: ", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim:  <built-in method dim of Tensor object at 0x000001BB68050CC0> shape:  torch.Size([2, 5])
